---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: git-pipelines
  type: git
  source:
    uri: https://github.com/concourse/pipelines.git

- name: git-concourse
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: master

- name: git-bosh
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh.git
    branch: master

- name: time-interval
  type: time
  source: {interval: 10m}

- name: bosh-io-concourse
  type: bosh-io-release
  source:
    repository: concourse/concourse

- name: bosh-io-cf-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-release

- name: bosh-io-cf-mysql-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-mysql-release

- name: bosh-io-garden-runc
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release

- name: bosh-io-bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh

- name: bosh-io-diego-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/diego-release

- name: bosh-io-postgres-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/postgres-release

- name: bosh-io-haproxy-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/haproxy-boshrelease

- name: bosh-io-shell-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/shell-boshrelease

- name: bosh-io-lemon-bosh
  type: bosh-io-release
  source:
    repository: pivotal-cf-experimental/bosh-lemon-release

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

jobs:
- name: so-many-resources
  plan:
  - aggregate:
    - get: git-pipelines
    - get: git-concourse
    - get: git-bosh
    - get: time-interval
    - get: bosh-io-concourse
      trigger: true
    - get: bosh-io-garden-runc
      trigger: true
    - get: bosh-io-bosh-release
    - get: bosh-io-diego-release
    - get: bosh-io-postgres-release
    - get: bosh-io-lemon-bosh
    - get: bosh-io-shell-release
    - get: bosh-io-cf-release
    - get: bosh-io-cf-mysql-release
    - get: bosh-io-haproxy-release
- name: get-more-resources
  plan:
  - get: git-pipelines
  - get: bosh-io-concourse
    passed: [so-many-resources]
    trigger: true
  - get: bosh-io-garden-runc
    passed: [so-many-resources]
    trigger: true
  - get: bosh-io-bosh-release
  - get: bosh-io-diego-release
  - get: bosh-io-postgres-release
  - get: gcp-stemcell
    trigger: true

- name: get-even-more-resources
  plan:
  - get: git-pipelines
  - get: bosh-io-concourse
    passed: [get-more-resources]
    trigger: true
  - get: bosh-io-garden-runc
    passed: [get-more-resources]
    trigger: true
  - get: bosh-io-bosh-release
  - get: bosh-io-diego-release
  - get: bosh-io-postgres-release
