resource_types:
- name: concourse-pipeline
  type: registry-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: pipelines
  type: git
  source:
    uri: https://github.com/concourse/pipelines

- name: ci.concourse-ci.org
  type: concourse-pipeline
  source:
    target: https://ci.concourse-ci.org
    teams:
    - name: main
      username: ((basic_auth.username))
      password: ((basic_auth.password))

jobs:
- name: reconfigure
  plan:
  - get: pipelines
    trigger: true
  - put: ci.concourse-ci.org
    params:
      pipelines:
      - name: main
        team: main
        config_file: pipelines/ci.concourse-ci.org/concourse.yml
      - name: images
        team: main
        config_file: pipelines/ci.concourse-ci.org/images.yml
      - name: wings
        team: main
        config_file: pipelines/ci.concourse-ci.org/wings.yml
      - name: prs
        team: main
        config_file: pipelines/ci.concourse-ci.org/pull-requests.yml
      - name: reconfigure-pipelines
        team: main
        config_file: pipelines/ci.concourse-ci.org/reconfigure-pipelines.yml
