groups: []
resources:
- name: resource-pr
  type: pull-request
  source:
    access_token: ((pull_requests_access_token))
    base: master
    repo: concourse/registry-image-resource
- name: alpine-edge
  type: docker-image
  source:
    repository: alpine
    tag: edge
- name: resource-repo
  type: git
  source:
    uri: https://github.com/concourse/registry-image-resource
- name: concourse
  type: git
  source:
    branch: master
    private_key: ((concourse_repo_private_key))
    uri: git@github.com:concourse/concourse.git
- name: resource-image
  type: docker-image
  source:
    password: ((docker.password))
    repository: concourse/registry-image-resource
    username: ((docker.username))
- name: golang-1.11
  type: docker-image
  source:
    repository: golang
    tag: 1.11-rc
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
jobs:
- name: build
  plan:
  - get: resource-repo
    trigger: true
  - get: golang-1.11
    trigger: true
    version: {digest: "sha256:cff5ee61b7629e795beb1e5b659cdc106498c9dd4448260a4aa8e4011b946c12"}
    params:
      save: true
  - get: alpine-edge
    trigger: true
    params:
      save: true
  - put: resource-image
    params:
      build: resource-repo
      load_bases: [alpine-edge, golang-1.11]
- name: prs
  public: true
  serial: true
  plan:
  - get: resource-pr
    trigger: true
    version: every
  - get: alpine-edge
    trigger: true
    params:
      save: true
  - put: resource-pr-merged
    resource: resource-pr
    params:
      path: resource-pr
      status: pending
    get_params:
      fetch_merge: true
  - put: resource-image
    params:
      build: resource-pr-merged
      load_base: alpine-edge
      tag: resource-pr/.git/id
      tag_prefix: pr-
    on_failure:
      put: resource-pr
      params:
        path: resource-pr
        status: failure
    on_success:
      put: resource-pr
      params:
        path: resource-pr
        status: success
- name: ship
  plan:
  - get: resource-repo
    passed:
    - build
    trigger: true
  - get: resource-image
    passed:
    - build
    trigger: true
    params:
      rootfs: true
  - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    params:
      BOSH_PRIVATE_CONFIG: ((concourse_release_private_config))
      RESOURCE_NAME: registry-image-resource
  - put: concourse
    params:
      rebase: true
      repository: bumped-concourse
