resources:
  - name: git-resource-image
    type: registry-image
    check_every: 1s
    source:
      repository: concourse/git-resource

  - name: s3-resource-image
    type: registry-image
    check_every: 1s
    source:
      repository: concourse/s3-resource

  - name: time-resource-image
    type: registry-image
    check_every: 1s
    source:
      repository: concourse/time-resource

  - name: semver-resource-image
    type: registry-image
    check_every: 1s
    source:
      repository: concourse/semver-resource

  - name: registry-image-resource-image
    type: registry-image
    check_every: 1s
    source:
      repository: concourse/registry-image-resource

  - name: tracker-resource-image
    type: registry-image
    check_every: 1s
    source:
      repository: concourse/tracker-resource

  - name: cf-resource-image
    type: registry-image
    check_every: 1s
    source:
      repository: concourse/cf-resource

  - name: archive-resource-image
    type: registry-image
    check_every: 1s
    source:
      repository: concourse/archive-resource

jobs:
  - name: 💩
    plan:
      - get: git-resource-image
      - get: s3-resource-image
      - get: time-resource-image
      - get: semver-resource-image
      - get: registry-image-resource-image
      - get: tracker-resource-image
      - get: cf-resource-image
      - get: archive-resource-image
