---
jobs:
- name: cpu-hog
  plan:
  - task: stress
    config:
      platform: linux

      image_resource:
        type: registry-image
        source: {repository: progrium/stress}

      run:
        path: stress
        args: [--cpu, 8, --timeout, 10s]

- name: mem-hog
  plan:
  - task: stress
    config:
      platform: linux

      image_resource:
        type: registry-image
        source: {repository: progrium/stress}

      run:
        path: stress
        args: [--vm, 2, --timeout, 10s]

- name: io-hog
  plan:
  - task: stress
    config:
      platform: linux

      image_resource:
        type: registry-image
        source: {repository: progrium/stress}

      run:
        path: stress
        args: [--io, 4, --timeout, 10s]

- name: disk-hog
  plan:
  - task: stress
    config:
      platform: linux

      image_resource:
        type: registry-image
        source: {repository: progrium/stress}

      run:
        path: stress
        args: [--hdd, 4, --timeout, 10s]

- name: net-hog
  plan:
  - task: stress
    config:
      platform: linux

      image_resource:
        type: registry-image
        source: {repository: concourse/buildroot, tag: curl}

      run:
        path: curl
        args: [-o, /dev/null, "http://speedtest.wdc01.softlayer.com/downloads/test500.zip"]
